---
- name: generate host file 
  blockinfile:
    path: /etc/hosts
    insertafter: EOF
    block: "{{ lookup('file', 'roles/common/files/hosts' )}}"

- name: install packages
  yum:
    name: vim
    state: latest

- name: disable selinux
  selinux:
    state: disabled

# This task already done with 
#- name: copy the publickey into all nodes 
#  authorized_key:
#    user: centos
#    state: present
#    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

#- name: create file
#  copy:
#    content: |
#            {
#               "insecure-registries": ["20.20.10.50:5000"]
#            }
#    dest: /etc/docker/daemon.json
