---
- name: install packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - git
    - epel-release

- name: git clone
  git:
    repo: 'https://github.com/ceph/ceph-ansible.git'
    dest: /home/ceph-ansible
    version: stable-4.0.25

- name: copy the private key
  copy:
    src: ~/.ssh/id_rsa
    dest: ~/.ssh/id_rsa
    mode: '0400'

- name: install package from epel-release
  yum:
    name: "{{ item }}"
    state: latest
  loop:
    - python-pip
    - ansible
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: add repo for docker
  yum_repository:
    name: docker-ce
    description: docker-ce
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
    gpgcheck: no

- name: install docker packages
  yum:
    name: "{{ item }}"
    state: latest
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: systemctl enable docker
  systemd:
    name: docker
    state: started
    enabled: true

- name: git clone from kolla repo
  git:
    repo: 'https://github.com/openstack/kolla.git'
    dest: /home/kolla
    version: stable/train
