---
- name: generate host file 
  blockinfile:
    path: /etc/hosts
    insertafter: EOF
    block: |
      20.20.10.50 kolla-deploy
      20.20.10.60 kolla-ctrl001
      20.20.10.61 kolla-ctrl002
      20.20.10.62 kolla-ctrl003
      20.20.10.63 kolla-com001
      20.20.10.70 kolla-ceph001
      20.20.10.71 kolla-ceph002
      20.20.10.72 kolla-ceph003

- name: install packages
  yum:
    name: vim
    state: latest

- name: disable selinux
  selinux:
    state: disabled

# This task already done with 
#- name: copy the publickey into all nodes 
#  authorized_key:
#    user: centos
#    state: present
#    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

#- name: create file
#  copy:
#    content: |
#            {
#               "insecure-registries": ["20.20.10.50:5000"]
#            }
#    dest: /etc/docker/daemon.json
